{
  "hash": "6c7f46563730ad3a1fb7f5bf0f3c8bf1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: |\n  | ECON 3201 \n  | Econometrics for Economics and Finance\nsubtitle: |\n    | Assignment 1\n    | Due Thursday October 8, 2026\nauthor: Maxim\nformat: \n  pdf:\n    include-in-header: \n      text: |\n        \\usepackage{fancyhdr}\n        \\fancypagestyle{style1}{\n        \\fancyhf{}\n        \\fancyfoot[C]{\\thepage}\n        \\renewcommand{\\headrulewidth}{0.4pt}\n        }\n\n        \\fancypagestyle{style2}{\n        \\fancyhf{}\n        \\fancyhead[R]{Assignment 1}\n        \\fancyhead[L]{ECON 3201}\n        \\fancyfoot[C]{\\thepage}\n        \\renewcommand{\\headrulewidth}{1pt}\n        }\n        \\pagestyle{style2}\ncallout-appearance: minimal\n---\n\n# Instructions {.unnumbered}\n\nAnswer all questions. Please complete your assignment using Quarto. Submit both your Quarto file and pdf output file.\n\n# Theory Questions\n\n## Q1\n\nCreate a personal Quarto website hosted on GitHub pages. For reference, please see the slides for **website** on Nexus. Your website should include the following:\n\ni.  An “Index” or “Home” page. This page should include the following:\n    - Your name\n    - Your photo (optional)\n    - Your credentials\n    - An “About Me” section that provides a brief (one paragraph) introduction to yourself. \\[10 Marks\\]\nii. A blog page. This will be the landing site for future assignments \\[5 Marks\\]\niii. Create a blog post and upload the finished PDF for this assignment. \\[3 Marks\\]\niv. Navigation bar with “Home” and \"Blog\" buttons. The navigation bar is edited in the “\\_quarto.yml” file. \\[2 Marks\\]\n\n::: callout-tip\n[Link to website](https://ihaveagitacc.github.io/website/)\n:::\n\n## Q2\n\nWrite your solutions using LaTeX. Show your work. You may use R to compute the answers.\n\nLet $X={1,2,3,4,5,6,7,8,9,10,11,12}$ be a uniformly distributed variable with probability distribution function $f_X(x)= \\frac{1}{12}$.\n\n> (a) Check that $f_X(x)$ is a true probability distribution.\n\n::: callout-tip\nEach outcome in the sample space has probability $\\frac{1}{12}$ of occurring. Since there are 12 outcomes in the sample space, it follows that the sum of probabilities adds up to 1. Thus, $f_X(x)$ is a true probability distribution.\n:::\n\n> (b) Compute the expected value of $X$.\n\n::: callout-tip\n$$1 \\times \\frac{1}{12} + 2 \\times \\frac{1}{12} + ... + 11 \\times \\frac{1}{12} + 12\\times \\frac{1}{12} = 6.5$$\n\nThe expected value of $X$ is 6.5.\n:::\n\n> (c) Compute the variance of $X$.\n\n::: callout-tip\n$$(1 - 6.5)^2 \\times \\frac{1}{12} + (2 - 6.5)^2 \\times \\frac{1}{12} + ... + (11 - 6.5)^2 \\times \\frac{1}{12} + (12 - 6.5)^2 \\times \\frac{1}{12} = 13$$\n\nThe variance of $X$ is 13.\n:::\n\n## Q3\n\nLet $X\\sim N(4,5)$. Find the probability of each event:\n\n(a) $Pr(X\\leq6)$\n\n::: callout-tip\n$Pr(X\\leq6)$ = 0.8144533\n:::\n\n(b) $Pr(X>4)$\n\n::: callout-tip\n$Pr(X>4)$ = 1 - $Pr(X\\leq4)$ = 0.5\n:::\n\n(c) $Pr(-1\\leq X< 1)$\n\n::: callout-tip\n$Pr(-1\\leq X< 1)$ = $Pr(X<1)$ - $Pr(-1\\leq X)$ = 0.07718259\n:::\n\n## Q4\n\nLet $Z\\sim N(0,1)$.\n\n(a) Compute $Pr(Z\\leq 0.83)$\n\n::: callout-tip\n$Pr(Z\\leq 0.83)$ = 0.7967306\n:::\n\n(b) Compute $Pr(-0.83 \\leq Z\\leq 0.83)$\n\n::: callout-tip\n$Pr(-0.83 \\leq Z\\leq 0.83)$ = $Pr(Z\\leq 0.83)$ - $Pr(-0.83 \\leq Z)$ = 0.5934612\n:::\n\n# R Exercises\n\n## Q5\n\nLet $X={1,2,3,4,5,6,7,8,9,10,11,12}$ be a uniformly distributed variable with probability distribution function $f_X(x)=1/12$.\n\n(a) Plot the probability distribution function $f_X(x)$ in R.\n\n::: callout-tip\n\n::: {.cell}\n\n```{.r .cell-code}\np <- rep(1/12, 12)\n\nplot(p, xlab = \"Outcome\", ylab = \"Probability\")\n```\n\n::: {.cell-output-display}\n![](econ_3201_a1_maxim_submission_files/figure-pdf/unnamed-chunk-1-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n(b) Plot the cumulative probability distribution function $f_X(x) in R$.\n\n::: callout-tip\n\n::: {.cell}\n\n```{.r .cell-code}\np <- rep(1/12, 12)\n\nc <- cumsum(p)\n\nplot(c, xlab = \"Outcome\", ylab = \"Cumulative Probability\")\n```\n\n::: {.cell-output-display}\n![](econ_3201_a1_maxim_submission_files/figure-pdf/unnamed-chunk-2-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n(c) Compute the expected value of $X$ in R.\n\n::: callout-tip\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 1:12\n\nmean(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.5\n```\n\n\n:::\n:::\n\n\n$E(X) = 6.5$\n:::\n\n(d) Compute the variance of $X$ in R.\n\n::: callout-tip\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 1:12\n\nvar(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13\n```\n\n\n:::\n:::\n\n\n$Var(X) = 13$\n:::\n\n## Q6\n\nThe standard normal distribution function is given by $$f(x)=\\frac{e^{-(x^2/2)}}{\\sqrt{2\\pi}\\sigma}$$\n\n(a) Define this function in R. (Note: $\\pi$ is coded as `pi` and $e$ is coded as `exp`.)\n\n::: callout-tip\n\n::: {.cell}\n\n```{.r .cell-code}\nsndf <- function(x) {\n  result <- exp(1)^(-(x^2/2))/sqrt(2 * pi)\n  return(result)\n}\n```\n:::\n\n:::\n\n(b) Integrate this function over the limit \\[$-\\infty,\\infty$\\] using the `integrate()` command in R. Infinity in R is written as `Inf`. To evaluate the integral, use `integrate()$value`\n\n::: callout-tip\n\n::: {.cell}\n\n```{.r .cell-code}\nintegrate(sndf, -Inf, Inf)$value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n:::\n\n(c) Compute the expected value of the standard normal distribution in R and confirm it is equal to 0.\n\n::: callout-tip\n\n::: {.cell}\n\n```{.r .cell-code}\nintegrate(function(x) x * sndf(x), -Inf, Inf)$value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nThe expected value of this function is equal to 0.\n:::\n\n(d) Compute the variance of the standard normal distribution in R and confirm it is equal to 1.\n\n::: callout-tip\n\n::: {.cell}\n\n```{.r .cell-code}\nintegrate(function(x) x^2 * sndf(x), -Inf, Inf)$value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\nThe variance of this function is equal to 1.\n:::\n\n(e) Compute $Pr(Z\\leq 0.83)$\n\n::: callout-tip\n\n::: {.cell}\n\n```{.r .cell-code}\nintegrate(sndf, -Inf, 0.83)$value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7967306\n```\n\n\n:::\n:::\n\n\n$Pr(Z\\leq 0.83) = 0.7967306$\n:::\n\n(f) Compute $Pr(-0.83 \\leq Z\\leq 0.83)$\n\n::: callout-tip\n\n::: {.cell}\n\n```{.r .cell-code}\nintegrate(sndf, -Inf, 0.83)$value - integrate(sndf, -Inf, -0.83)$value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5934612\n```\n\n\n:::\n:::\n\n\n$Pr(-0.83 \\leq Z\\leq 0.83) = 0.5934612$\n:::\n\n(g) Compute $Pr(-0.83 \\leq Z\\leq 0.83)$ using the `pnorm()` command and compare your results to (f).\n\n::: callout-tip\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(0.83) - pnorm(-0.83)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5934612\n```\n\n\n:::\n:::\n\n\n$Pr(-0.83 \\leq Z\\leq 0.83) = 0.5934612$\n\nThe result of using `pnorm()` is the same as the result in (f).\n:::\n\n## Q7\n\nLet $X$ denote the prison sentence, in years, for people convicted of auto theft in a particular province in Canada. Suppose the PDF of $X$ is given by: $$f(X)=\\frac{1}{9}x^2,\\text{ }0<x<3.$$\n\n(a) Define $f(x)$ in R.\n\n::: callout-tip\n\n::: {.cell}\n\n```{.r .cell-code}\nf <- function(x) {\n  result <- (1/9) * x^2\n  return(result)\n}\n```\n:::\n\n:::\n\n(b) Integrate $f(x)$ over the interval \\[0,3\\].\n\n::: callout-tip\n\n::: {.cell}\n\n```{.r .cell-code}\nintegrate(f, 0, 3)$value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n:::\n\n(c) Compute the expected prison sentence.\n\n::: callout-tip\n\n::: {.cell}\n\n```{.r .cell-code}\nintegrate(function(x) x * f(x), 0, 3)$value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.25\n```\n\n\n:::\n:::\n\n\nThe expected prison sentence is 2.25 years.\n:::\n\n## Q8\n\nLet $X$ follow a Student $t$ distribution with $M$ degrees of freedom. Then $$X=\\frac{Z}{\\sqrt{W/M}}\\sim t_M,$$ where $Z$ is a standard normal variable and $W$ is a chi-squared variable with $M$ degrees of freedom.\n\n(a) On the same figure plot the following:\n    (i) Plot the standard normal probability distribution using `curve()`. Specify the range as \\[-5,5\\] using `xlim`. Name the `ylab` \"Density\". The main title should be \"Densities of t Distribution\".\n    (ii) Plot the Student t distribution with 5 degrees of freedom using `curve()` and `dt()`. Specify the range as \\[-5,5\\] using `xlim`. Choose a different colour, i.e. `col=2`. To learn more about `dt`, type `?dt` in your console.\n    (iii) Plot the Student t distribution with 15 degrees of freedom using `curve()` and `dt()`. Specify the range as \\[-5,5\\] using `xlim`. Choose a different colour, i.e. `col=3`. To learn more about `dt`, type `?dt` in your console.\n    (iv) Plot the Student t distribution with 25 degrees of freedom using `curve()` and `dt()`. Specify the range as \\[-5,5\\] using `xlim`. Choose a different colour, i.e. `col=4`. To learn more about `dt`, type `?dt` in your console.\n    (v) Include the following legend in your plot:\\\n        `legend(\"topright\",`  `c(\"N(0, 1)\", \"M=2\", \"M=4\", \"M=25\"),`  `col = 1:4,`  `lty = c(1, 1, 1, 1))`\\\n\n::: callout-tip\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve(dnorm(x),\n      main = \"Densities of t Distribution\",\n      ylab = \"Density\",\n      xlim = c(-5, 5))\n\ncurve(dt(x, 5, log = FALSE),\n      add = TRUE,\n      xlim = c(-5, 5),\n      col = 2)\n\ncurve(dt(x, 15, log = FALSE),\n      add = TRUE,\n      xlim = c(-5, 5),\n      col = 3)\n\ncurve(dt(x, 25, log = FALSE),\n      add = TRUE,\n      xlim = c(-5, 5),\n      col = 4)\n\nlegend(\"topright\",\n       c(\"N(0, 1)\",\n         \"M = 5\", \n         \"M = 15\", \n         \"M = 25\"),\n       col = 1:4,\n       lty = c(1, 1, 1, 1))\n```\n\n::: {.cell-output-display}\n![](econ_3201_a1_maxim_submission_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-pos='H'}\n:::\n:::\n\n:::\n\n(b) What do you observe as the degrees of freedom increase?\n\n::: callout-tip\nAs the degrees of freedom increase, the student t distribution approaches that of the standard normal distribution.\n:::\n",
    "supporting": [
      "econ_3201_a1_maxim_submission_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}